# Meta
# ------------------
site_name: Dooit
repo_url: https://github.com/kraanzu/dooit/
site_description: Documentation for dooit
site_author: kraanzu
copyright: kraanzu

theme:
  name: material
  locale: en
  # logo: <use dooits logo>
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.footer
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Navbar
# ------------------
nav:
  - Home: 'index.md'

# Footer
# ------------------
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kraanzu
      name: Kraanzu on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/kraanzu/dooit/
      name: Dooit on Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/WA2ER9MBWa
      name: Kraanzu's Cafe

copyright: Copyright &copy; Kraanzu
